impl #870
DGP-Studio/Snap.Hutao pull request #1169
Opened 2023-12-11 06:32 UTC by qhy040404

2023-12-11 07:13 UTC, Lightczx requested changes

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/View/Dialog/QrCodeDialog.xaml.cs
> +    private async ValueTask Initialize()
This method has a body which is too large

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Factory/QrCode/IQrCodeFactory.cs
> +    byte[] CreateByteArr(string source);
Method Name

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/View/Dialog/QrCodeDialog.xaml.cs
> +            using (PeriodicTimer timer = new(TimeSpan.FromSeconds(3)))
二维码存在1分钟的过期时间，需要处理

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/ViewModel/User/UserViewModel.cs
> +    private async Task LoginQrCode()
Method Name

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/ApiEndpoints.cs
> +    public const string STokenByGameToken = $"{ApiTakumiAccountSessionApp}/getTokenByGameToken";
应该使用 passport host下的 api

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/ApiEndpoints.cs
> +    private const string ApiTakumiAccountSessionApp = $"{ApiTakumi}/account/ma-cn-session/app";
这个 api 理论上也应该在 passport 下

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeAccount.cs
> +internal sealed class QrCodeAccount
UidGameToken

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeClient.cs
> +    private readonly string device = Core.Random.GetLetterAndNumberString(64);
应该移动至 HoyolabOptions 下

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeQuery.cs
> +internal sealed class QrCodeQuery
GameLoginResult

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeAccount.cs
> +internal sealed class QrCodeAccount
or UidToken

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeFetchOptions.cs
> +    public QrCodeFetchOptions(int appId, string device)
避免使用带有参数的构造器
使用 ClassName.Create 模式

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeQueryStatus.cs
> +internal sealed partial class QrCodeQueryStatus
enum

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Takumi/Account/SessionAppClient.cs
> +    public async ValueTask<Response<LoginResult>> PostSTokenByGameTokenAsync(QrCodeAccount account, CancellationToken token = default)
移动至 Pasport Client

2023-12-11 07:13 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Response/KnownReturnCode.cs
> +    QrCodeExpired = -106,
顺序

2023-12-11 07:21 UTC, Lightczx requested changes

2023-12-11 07:21 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/Web/Hoyolab/Hk4e/QrCode/QrCodeFetchOptions.cs
> +internal sealed class QrCodeFetchOptions
GameLoginRequest

2023-12-11 09:59 UTC, qhy040404 commented on src/Snap.Hutao/Snap.Hutao/View/Dialog/QrCodeDialog.xaml.cs
> +            using (PeriodicTimer timer = new(TimeSpan.FromSeconds(3)))
这个在下面有过期处理

2023-12-12 06:25 UTC, Lightczx approved these changes

2023-12-12 06:25 UTC, merged