实现对材料统计页面中的材料做初步排序。
DGP-Studio/Snap.Hutao pull request #1510
Opened 2024-03-25 13:14 UTC by GoddessLuBoYan

更细致的排序、分类功能，需要集成观测枢功能才能进行。#1427 #1394

2024-03-25 13:16 UTC, Lightczx requested changes

2024-03-25 13:16 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/ViewModel/Cultivation/CultivationViewModel.cs
> +            if (x.Inner.Name == "摩拉") { return -1; }
未适配全部语言

2024-03-25 13:19 UTC, GoddessLuBoYan commented on src/Snap.Hutao/Snap.Hutao/ViewModel/Cultivation/CultivationViewModel.cs
> +            if (x.Inner.Name == "摩拉") { return -1; }
好的

2024-03-25 13:25 UTC, GoddessLuBoYan commented on src/Snap.Hutao/Snap.Hutao/ViewModel/Cultivation/CultivationViewModel.cs
> +            if (x.Inner.Name == "摩拉") { return -1; }
已修复

2024-03-27 06:38 UTC, Lightczx requested changes

2024-03-27 06:38 UTC, Lightczx commented on src/Snap.Hutao/Snap.Hutao/ViewModel/Cultivation/CultivationViewModel.cs
> +                if (statistics is not null)
既然在获取statistics后立即进行了排序，为什么没有考虑直接在Service里面排序完了再赋值呢

2024-03-27 07:20 UTC, GoddessLuBoYan commented on src/Snap.Hutao/Snap.Hutao/ViewModel/Cultivation/CultivationViewModel.cs
> +                if (statistics is not null)
不敢动，怕出现隐藏bug；此外，后续个人希望按照观测枢的数据分类再排序，这一次排序做的事就有点多了，考虑一个函数只做一件事，我就没有直接改service本身的实现，保证service的返回值是绝对原始的返回值

不过你说没问题的话，就可以改

2024-03-28 05:32 UTC, merged